blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/heckseven/dark-matrix/discussions
    about: For open-ended questions or discussion, use Discussions rather than an issue.
